<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net8.0-windows</TargetFramework>
    <UseWPF>true</UseWPF>
    <RuntimeIdentifier>win-x64</RuntimeIdentifier>
    <AppendRuntimeIdentifierToOutputPath>false</AppendRuntimeIdentifierToOutputPath>
    <CopyLocalLockFileAssemblies>true</CopyLocalLockFileAssemblies>
    <NoWarn>CA1416</NoWarn>
  </PropertyGroup>
  <ItemGroup>
    <None Remove="Assets\GSC_BEDROCKGDB_P_ORGANIZATION_V2_10.csv" />
    <None Remove="Assets\GSC_BEDROCKGDB_SCHEMA_V2_10.json" />
    <None Remove="Assets\GSC_BEDROCKGDB_SYMBOL_GEOLINES_V2_10.csv" />
    <None Remove="Assets\GSC_BEDROCKGDB_SYMBOL_GEOPOINTS_V2_10.csv" />
    <None Remove="Assets\GSC_SymbolStandard.stylx" />
    <None Remove="Assets\P_ORGANIZATION.csv" />
    <None Remove="Config.daml" />
    <None Remove="Images\ANNO_BRACKET.png" />
    <None Remove="Images\ANNO_BREAK.png" />
    <None Remove="Images\BEACH.png" />
    <None Remove="Images\BLOB.png" />
    <None Remove="Images\BREAK.png" />
    <None Remove="Images\DUNES.png" />
    <None Remove="Images\Hammer16.png" />
    <None Remove="Images\Hammer32.png" />
    <None Remove="Images\HEADING1.png" />
    <None Remove="Images\HEADING2.png" />
    <None Remove="Images\HEADING3.png" />
    <None Remove="Images\HEADING4.png" />
    <None Remove="Images\HEADING5.png" />
    <None Remove="Images\LANDSLIDE.png" />
    <None Remove="Images\LINE.png" />
    <None Remove="Images\L_BRACKET_L.png" />
    <None Remove="Images\L_BRACKET_U.png" />
    <None Remove="Images\MORAINES.png" />
    <None Remove="Images\OVERLAY.png" />
    <None Remove="Images\POINT_CC.png" />
    <None Remove="Images\POINT_CC_45.png" />
    <None Remove="Images\POINT_LC_45.png" />
    <None Remove="Images\R_BRACKET_L.png" />
    <None Remove="Images\R_BRACKET_U.png" />
    <None Remove="Images\TWOSIDE.png" />
    <None Remove="Images\TWOSIDE_FLIP.png" />
    <None Remove="Images\TWOSIDE_FLOW.png" />
    <None Remove="Images\UNIT_BOX.png" />
    <None Remove="Images\UNIT_CHILD.png" />
    <None Remove="Images\UNIT_CHILD_LINE.png" />
    <None Remove="Images\UNIT_INDENT.png" />
    <None Remove="Images\UNIT_INDENT2.png" />
    <None Remove="Images\UNIT_LINE.png" />
    <None Remove="Images\UNIT_PARENT.png" />
    <None Remove="Images\UNIT_SPLIT.png" />
    <None Remove="Images\WAVE.png" />
  </ItemGroup>
  <ItemGroup>
    <Content Include="Config.daml" />    
    <Content Include="Images\AddInDesktop16.png" />
    <Content Include="Images\AddInDesktop32.png" />
    <Content Include="DarkImages\AddInDesktop16.png" />
    <Content Include="DarkImages\AddInDesktop32.png" />
    <Resource Include="Images\ANNO_BRACKET.png">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </Resource>
    <Resource Include="Images\ANNO_BREAK.png">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </Resource>
    <Resource Include="Images\BEACH.png">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </Resource>
    <Resource Include="Images\BLOB.png">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </Resource>
    <Resource Include="Images\BREAK.png">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </Resource>
    <Resource Include="Images\DUNES.png">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </Resource>
    <Resource Include="Images\Hammer16.png">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </Resource>
    <Resource Include="Images\HEADING1.png">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </Resource>
    <Resource Include="Images\HEADING2.png">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </Resource>
    <Resource Include="Images\HEADING3.png">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </Resource>
    <Resource Include="Images\HEADING4.png">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </Resource>
    <Resource Include="Images\HEADING5.png">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </Resource>
    <Resource Include="Images\LANDSLIDE.png">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </Resource>
    <Resource Include="Images\LINE.png">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </Resource>
    <Resource Include="Images\L_BRACKET_L.png">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </Resource>
    <Resource Include="Images\L_BRACKET_U.png">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </Resource>
    <Resource Include="Images\MORAINES.png">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </Resource>
    <Resource Include="Images\OVERLAY.png">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </Resource>
    <Resource Include="Images\POINT_CC.png">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </Resource>
    <Resource Include="Images\POINT_CC_45.png">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </Resource>
    <Resource Include="Images\POINT_LC_45.png">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </Resource>
    <Resource Include="Images\R_BRACKET_L.png">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </Resource>
    <Resource Include="Images\R_BRACKET_U.png">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </Resource>
    <Resource Include="Images\TWOSIDE.png">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </Resource>
    <Resource Include="Images\TWOSIDE_FLIP.png">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </Resource>
    <Resource Include="Images\TWOSIDE_FLOW.png">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </Resource>
    <Resource Include="Images\UNIT_BOX.png">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </Resource>
    <Resource Include="Images\UNIT_CHILD.png">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </Resource>
    <Resource Include="Images\UNIT_CHILD_LINE.png">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </Resource>
    <Resource Include="Images\UNIT_INDENT.png">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </Resource>
    <Resource Include="Images\UNIT_INDENT2.png">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </Resource>
    <Resource Include="Images\UNIT_LINE.png">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </Resource>
    <Resource Include="Images\UNIT_PARENT.png">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </Resource>
    <Resource Include="Images\UNIT_SPLIT.png">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </Resource>
    <Resource Include="Images\WAVE.png">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </Resource>
    <Resource Include="Images\Hammer32.png">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </Resource>    
  </ItemGroup>
  <ItemGroup>
    <EmbeddedResource Include="Assets\GSC_BEDROCKGDB_P_ORGANIZATION_V2_10.csv" />
    <EmbeddedResource Include="Assets\GSC_BEDROCKGDB_SCHEMA_V2_10.json" />
    <EmbeddedResource Include="Assets\GSC_BEDROCKGDB_SYMBOL_GEOLINES_V2_10.csv" />
    <EmbeddedResource Include="Assets\GSC_BEDROCKGDB_SYMBOL_GEOPOINTS_V2_10.csv" />
    <EmbeddedResource Include="Assets\GSC_SymbolStandard.stylx" />
  </ItemGroup>
  <ItemGroup>
    <None Include="Properties\launchSettings.json" />
  </ItemGroup>
  <ItemGroup>
    <PackageReference Include="sqlite-net-pcl" Version="1.9.172" />
  </ItemGroup>
  <ItemGroup>
    <Reference Include="ArcGIS.Desktop.Framework">
      <HintPath>C:\Users\ghuotvez\AppData\Local\Programs\ArcGIS\Pro\bin\ArcGIS.Desktop.Framework.dll</HintPath>
      <CopyLocal>False</CopyLocal>
      <Private>False</Private>
    </Reference>
    <Reference Include="ArcGIS.Core">
      <HintPath>C:\Users\ghuotvez\AppData\Local\Programs\ArcGIS\Pro\bin\ArcGIS.Core.dll</HintPath>
      <CopyLocal>False</CopyLocal>
      <Private>False</Private>
    </Reference>
    <Reference Include="ArcGIS.Desktop.Core">
      <HintPath>C:\Users\ghuotvez\AppData\Local\Programs\ArcGIS\Pro\bin\Extensions\Core\ArcGIS.Desktop.Core.dll</HintPath>
      <CopyLocal>False</CopyLocal>
      <Private>False</Private>
    </Reference>
    <Reference Include="ArcGIS.Desktop.Mapping">
      <HintPath>C:\Users\ghuotvez\AppData\Local\Programs\ArcGIS\Pro\bin\Extensions\Mapping\ArcGIS.Desktop.Mapping.dll</HintPath>
      <CopyLocal>False</CopyLocal>
      <Private>False</Private>
    </Reference>
    <Reference Include="ArcGIS.Desktop.Catalog">
      <HintPath>C:\Users\ghuotvez\AppData\Local\Programs\ArcGIS\Pro\bin\Extensions\Catalog\ArcGIS.Desktop.Catalog.dll</HintPath>
      <CopyLocal>False</CopyLocal>
      <Private>False</Private>
    </Reference>
    <Reference Include="ArcGIS.Desktop.Editing">
      <HintPath>C:\Users\ghuotvez\AppData\Local\Programs\ArcGIS\Pro\bin\Extensions\Editing\ArcGIS.Desktop.Editing.dll</HintPath>
      <CopyLocal>False</CopyLocal>
      <Private>False</Private>
    </Reference>
    <Reference Include="ArcGIS.Desktop.Extensions">
      <HintPath>C:\Users\ghuotvez\AppData\Local\Programs\ArcGIS\Pro\bin\Extensions\DesktopExtensions\ArcGIS.Desktop.Extensions.dll</HintPath>
      <CopyLocal>False</CopyLocal>
      <Private>False</Private>
    </Reference>
    <Reference Include="ArcGIS.Desktop.GeoProcessing">
      <HintPath>C:\Users\ghuotvez\AppData\Local\Programs\ArcGIS\Pro\bin\Extensions\GeoProcessing\ArcGIS.Desktop.GeoProcessing.dll</HintPath>
      <CopyLocal>False</CopyLocal>
      <Private>False</Private>
    </Reference>
    <Reference Include="ArcGIS.Desktop.Layouts">
      <HintPath>C:\Users\ghuotvez\AppData\Local\Programs\ArcGIS\Pro\bin\Extensions\Layout\ArcGIS.Desktop.Layouts.dll</HintPath>
      <CopyLocal>False</CopyLocal>
      <Private>False</Private>
    </Reference>
	<Reference Include="ArcGIS.Desktop.KnowledgeGraph">
		<HintPath>C:\Users\ghuotvez\AppData\Local\Programs\ArcGIS\Pro\bin\Extensions\KnowledgeGraph\ArcGIS.Desktop.KnowledgeGraph.dll</HintPath>
		<CopyLocal>False</CopyLocal>
		<Private>False</Private>
	</Reference>
	<Reference Include="ArcGIS.Desktop.Shared.Wpf">
        <HintPath>C:\Users\ghuotvez\AppData\Local\Programs\ArcGIS\Pro\bin\ArcGIS.Desktop.Shared.Wpf.dll</HintPath>
        <CopyLocal>False</CopyLocal>
        <Private>False</Private>
    </Reference>
    <Reference Include="ArcGIS.Desktop.Ribbon.Wpf">
      <HintPath>C:\Users\ghuotvez\AppData\Local\Programs\ArcGIS\Pro\bin\ArcGIS.Desktop.Ribbon.Wpf.dll</HintPath>
      <CopyLocal>False</CopyLocal>
      <Private>False</Private>
    </Reference>
    <Reference Include="ArcGIS.Desktop.DataGrid.Contrib.Wpf">
      <HintPath>C:\Users\ghuotvez\AppData\Local\Programs\ArcGIS\Pro\bin\ArcGIS.Desktop.DataGrid.Contrib.Wpf.dll</HintPath>
      <CopyLocal>False</CopyLocal>
      <Private>False</Private>
    </Reference>
    <Reference Include="ArcGIS.Desktop.Resources">
      <HintPath>C:\Users\ghuotvez\AppData\Local\Programs\ArcGIS\Pro\bin\ArcGIS.Desktop.Resources.dll</HintPath>
      <CopyLocal>False</CopyLocal>
      <Private>False</Private>
    </Reference>
  </ItemGroup>
  <ItemGroup>
    <Compile Update="Properties\Resources.Designer.cs">
      <DesignTime>True</DesignTime>
      <AutoGen>True</AutoGen>
      <DependentUpon>Resources.resx</DependentUpon>
    </Compile>
    <Compile Update="Properties\Settings.Designer.cs">
      <DesignTimeSharedInput>True</DesignTimeSharedInput>
      <AutoGen>True</AutoGen>
      <DependentUpon>Settings.settings</DependentUpon>
    </Compile>
  </ItemGroup>
  <ItemGroup>
    <EmbeddedResource Update="Properties\Resources.fr.resx">
      <Generator>PublicResXFileCodeGenerator</Generator>
    </EmbeddedResource>
    <EmbeddedResource Update="Properties\Resources.resx">
      <Generator>PublicResXFileCodeGenerator</Generator>
      <LastGenOutput>Resources.Designer.cs</LastGenOutput>
    </EmbeddedResource>
  </ItemGroup>
  <ItemGroup>
    <None Update="Properties\Settings.settings">
      <Generator>SettingsSingleFileGenerator</Generator>
      <LastGenOutput>Settings.Designer.cs</LastGenOutput>
    </None>
  </ItemGroup>
   <Import Project="C:\Users\ghuotvez\AppData\Local\Programs\ArcGIS\Pro\bin\Esri.ProApp.SDK.Desktop.targets" Condition="Exists('C:\Users\ghuotvez\AppData\Local\Programs\ArcGIS\Pro\bin\Esri.ProApp.SDK.Desktop.targets') AND !Exists('Esri.ArcGISPro.Extensions.targets')" />
</Project>
