//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BedrockEditorPro.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("BedrockEditorPro.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New File Geodatabase.
        /// </summary>
        public static string DialogFGDBSavePromptTitle {
            get {
                return ResourceManager.GetString("DialogFGDBSavePromptTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select a projection.
        /// </summary>
        public static string DialogProjectionPromptTitle {
            get {
                return ResourceManager.GetString("DialogProjectionPromptTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to XML File.
        /// </summary>
        public static string DialogXMLPromptTitle {
            get {
                return ResourceManager.GetString("DialogXMLPromptTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Default Embedded (XML Version 10.2).
        /// </summary>
        public static string FormEnvironmentNewGeodatabaseCheckbox {
            get {
                return ResourceManager.GetString("FormEnvironmentNewGeodatabaseCheckbox", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Input Project Template (.xml).
        /// </summary>
        public static string FormEnvironmentNewGeodatabaseInput1 {
            get {
                return ResourceManager.GetString("FormEnvironmentNewGeodatabaseInput1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Output Database Path.
        /// </summary>
        public static string FormEnvironmentNewGeodatabaseInput2 {
            get {
                return ResourceManager.GetString("FormEnvironmentNewGeodatabaseInput2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Projection.
        /// </summary>
        public static string FormEnvironmentNewGeodatabaseInput3 {
            get {
                return ResourceManager.GetString("FormEnvironmentNewGeodatabaseInput3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create Project Geodatabase.
        /// </summary>
        public static string FormEnvironmentNewGeodatabaseTitle {
            get {
                return ResourceManager.GetString("FormEnvironmentNewGeodatabaseTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Database already exists..
        /// </summary>
        public static string FormEnvironmentNewGeodatabaseWarningDBExist {
            get {
                return ResourceManager.GetString("FormEnvironmentNewGeodatabaseWarningDBExist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Browse.
        /// </summary>
        public static string GenericButtonBrowse {
            get {
                return ResourceManager.GetString("GenericButtonBrowse", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancel.
        /// </summary>
        public static string GenericButtonCancel {
            get {
                return ResourceManager.GetString("GenericButtonCancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Run.
        /// </summary>
        public static string GenericButtonRun {
            get {
                return ResourceManager.GetString("GenericButtonRun", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save.
        /// </summary>
        public static string GenericButtonSave {
            get {
                return ResourceManager.GetString("GenericButtonSave", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Process completed.
        /// </summary>
        public static string GenericMessageCompleted {
            get {
                return ResourceManager.GetString("GenericMessageCompleted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error: see debug file for more information..
        /// </summary>
        public static string GenericMessageError {
            get {
                return ResourceManager.GetString("GenericMessageError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        public static byte[] GSC_BEDROCKGDB_P_ORGANIZATION_V2_10 {
            get {
                object obj = ResourceManager.GetObject("GSC_BEDROCKGDB_P_ORGANIZATION_V2_10", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        public static byte[] GSC_BEDROCKGDB_SCHEMA_V2_10 {
            get {
                object obj = ResourceManager.GetObject("GSC_BEDROCKGDB_SCHEMA_V2_10", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        public static byte[] GSC_BEDROCKGDB_SYMBOL_GEOLINES_V2_10 {
            get {
                object obj = ResourceManager.GetObject("GSC_BEDROCKGDB_SYMBOL_GEOLINES_V2_10", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        public static byte[] GSC_BEDROCKGDB_SYMBOL_GEOPOINTS_V2_10 {
            get {
                object obj = ResourceManager.GetObject("GSC_BEDROCKGDB_SYMBOL_GEOPOINTS_V2_10", resourceCulture);
                return ((byte[])(obj));
            }
        }
    }
}
