//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BedrockEditorPro.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("BedrockEditorPro.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select database source to build layers from.
        /// </summary>
        public static string ButtonEnvironmentAddProjectLayersPromptTitle {
            get {
                return ResourceManager.GetString("ButtonEnvironmentAddProjectLayersPromptTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Project layers.
        /// </summary>
        public static string ButtonEnvironmentAddProjectLayersTitle {
            get {
                return ResourceManager.GetString("ButtonEnvironmentAddProjectLayersTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select File Geodatabase to add Topology to:.
        /// </summary>
        public static string ButtonEnvironmentTopologicalRulesPromptTitle {
            get {
                return ResourceManager.GetString("ButtonEnvironmentTopologicalRulesPromptTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Topological rules.
        /// </summary>
        public static string ButtonEnvironmentTopologicalRulesTitle {
            get {
                return ResourceManager.GetString("ButtonEnvironmentTopologicalRulesTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select File Geodatabase.
        /// </summary>
        public static string DialogFGDBPromptTitle {
            get {
                return ResourceManager.GetString("DialogFGDBPromptTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New File Geodatabase.
        /// </summary>
        public static string DialogFGDBSavePromptTitle {
            get {
                return ResourceManager.GetString("DialogFGDBSavePromptTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select a projection.
        /// </summary>
        public static string DialogProjectionPromptTitle {
            get {
                return ResourceManager.GetString("DialogProjectionPromptTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to XML File.
        /// </summary>
        public static string DialogXMLPromptTitle {
            get {
                return ResourceManager.GetString("DialogXMLPromptTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Default Embedded Model (XML Version 10.2).
        /// </summary>
        public static string FormEnvironmentNewGeodatabaseCheckbox {
            get {
                return ResourceManager.GetString("FormEnvironmentNewGeodatabaseCheckbox", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Input Project Template (.xml).
        /// </summary>
        public static string FormEnvironmentNewGeodatabaseInput1 {
            get {
                return ResourceManager.GetString("FormEnvironmentNewGeodatabaseInput1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Output Database Path.
        /// </summary>
        public static string FormEnvironmentNewGeodatabaseInput2 {
            get {
                return ResourceManager.GetString("FormEnvironmentNewGeodatabaseInput2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Projection.
        /// </summary>
        public static string FormEnvironmentNewGeodatabaseInput3 {
            get {
                return ResourceManager.GetString("FormEnvironmentNewGeodatabaseInput3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create Project Geodatabase.
        /// </summary>
        public static string FormEnvironmentNewGeodatabaseTitle {
            get {
                return ResourceManager.GetString("FormEnvironmentNewGeodatabaseTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Database already exists..
        /// </summary>
        public static string FormEnvironmentNewGeodatabaseWarningDBExist {
            get {
                return ResourceManager.GetString("FormEnvironmentNewGeodatabaseWarningDBExist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Input study area layer.
        /// </summary>
        public static string FormLoadStudyAreaLayer {
            get {
                return ResourceManager.GetString("FormLoadStudyAreaLayer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name.
        /// </summary>
        public static string FormLoadStudyAreaName {
            get {
                return ResourceManager.GetString("FormLoadStudyAreaName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Purpose.
        /// </summary>
        public static string FormLoadStudyAreaPurpose {
            get {
                return ResourceManager.GetString("FormLoadStudyAreaPurpose", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Purpose Value.
        /// </summary>
        public static string FormLoadStudyAreaPurposeValues {
            get {
                return ResourceManager.GetString("FormLoadStudyAreaPurposeValues", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Remarks.
        /// </summary>
        public static string FormLoadStudyAreaRemark {
            get {
                return ResourceManager.GetString("FormLoadStudyAreaRemark", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Study Areas.
        /// </summary>
        public static string FormLoadStudyAreaTitle {
            get {
                return ResourceManager.GetString("FormLoadStudyAreaTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Browse.
        /// </summary>
        public static string GenericButtonBrowse {
            get {
                return ResourceManager.GetString("GenericButtonBrowse", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancel.
        /// </summary>
        public static string GenericButtonCancel {
            get {
                return ResourceManager.GetString("GenericButtonCancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Run.
        /// </summary>
        public static string GenericButtonRun {
            get {
                return ResourceManager.GetString("GenericButtonRun", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save.
        /// </summary>
        public static string GenericButtonSave {
            get {
                return ResourceManager.GetString("GenericButtonSave", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Process completed.
        /// </summary>
        public static string GenericMessageCompleted {
            get {
                return ResourceManager.GetString("GenericMessageCompleted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error: see debug file for more information..
        /// </summary>
        public static string GenericMessageError {
            get {
                return ResourceManager.GetString("GenericMessageError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error.
        /// </summary>
        public static string GenericMessageErrorTitle {
            get {
                return ResourceManager.GetString("GenericMessageErrorTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to BEDROCK.
        /// </summary>
        public static string GroupLayerBedrock {
            get {
                return ResourceManager.GetString("GroupLayerBedrock", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to INTERPRETATION.
        /// </summary>
        public static string GroupLayerInterpretation {
            get {
                return ResourceManager.GetString("GroupLayerInterpretation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Map Index.
        /// </summary>
        public static string GroupLayerInterpretationCGM {
            get {
                return ResourceManager.GetString("GroupLayerInterpretationCGM", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Geolines.
        /// </summary>
        public static string GroupLayerInterpretationGeoline {
            get {
                return ResourceManager.GetString("GroupLayerInterpretationGeoline", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Geopoints.
        /// </summary>
        public static string GroupLayerInterpretationGeopoint {
            get {
                return ResourceManager.GetString("GroupLayerInterpretationGeopoint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Map Units.
        /// </summary>
        public static string GroupLayerInterpretationGeopoly {
            get {
                return ResourceManager.GetString("GroupLayerInterpretationGeopoly", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Labels.
        /// </summary>
        public static string GroupLayerInterpretationLabel {
            get {
                return ResourceManager.GetString("GroupLayerInterpretationLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PROJECT.
        /// </summary>
        public static string GroupLayerProject {
            get {
                return ResourceManager.GetString("GroupLayerProject", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SOURCE.
        /// </summary>
        public static string GroupLayerSource {
            get {
                return ResourceManager.GetString("GroupLayerSource", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Study Areas.
        /// </summary>
        public static string GroupLayerSourceStudyArea {
            get {
                return ResourceManager.GetString("GroupLayerSourceStudyArea", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to VALIDATION.
        /// </summary>
        public static string GroupLayerValidation {
            get {
                return ResourceManager.GetString("GroupLayerValidation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Topology.
        /// </summary>
        public static string GroupLayerValidationTopology {
            get {
                return ResourceManager.GetString("GroupLayerValidationTopology", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to VISUALIZATION.
        /// </summary>
        public static string GroupLayerVisualization {
            get {
                return ResourceManager.GetString("GroupLayerVisualization", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        public static byte[] GSC_BEDROCKGDB_P_ORGANIZATION_V2_10 {
            get {
                object obj = ResourceManager.GetObject("GSC_BEDROCKGDB_P_ORGANIZATION_V2_10", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        public static byte[] GSC_BEDROCKGDB_SCHEMA_V2_10 {
            get {
                object obj = ResourceManager.GetObject("GSC_BEDROCKGDB_SCHEMA_V2_10", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        public static byte[] GSC_BEDROCKGDB_SYMBOL_GEOLINES_V2_10 {
            get {
                object obj = ResourceManager.GetObject("GSC_BEDROCKGDB_SYMBOL_GEOLINES_V2_10", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        public static byte[] GSC_BEDROCKGDB_SYMBOL_GEOPOINTS_V2_10 {
            get {
                object obj = ResourceManager.GetObject("GSC_BEDROCKGDB_SYMBOL_GEOPOINTS_V2_10", resourceCulture);
                return ((byte[])(obj));
            }
        }
    }
}
