//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GSC_ProjectEditor.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("GSC_ProjectEditor.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select a database containing Ganfeld data..
        /// </summary>
        internal static string Dialog_DescriptionGanfeldDB {
            get {
                return ResourceManager.GetString("Dialog_DescriptionGanfeldDB", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter a new project folder name..
        /// </summary>
        internal static string Dialog_DescriptionProjectFolder {
            get {
                return ResourceManager.GetString("Dialog_DescriptionProjectFolder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select desire source file..
        /// </summary>
        internal static string Dialog_DescriptionSource {
            get {
                return ResourceManager.GetString("Dialog_DescriptionSource", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Choose one.
        /// </summary>
        internal static string Dialog_NewParticipantLabel {
            get {
                return ResourceManager.GetString("Dialog_NewParticipantLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select a Person.
        /// </summary>
        internal static string Dialog_NewParticipantTitle {
            get {
                return ResourceManager.GetString("Dialog_NewParticipantTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select a folder containing Ganfeld Shapefiles..
        /// </summary>
        internal static string Dialog_SelectGanfeldShapefileFolder {
            get {
                return ResourceManager.GetString("Dialog_SelectGanfeldShapefileFolder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select a folder containing Ganfeld LUT files..
        /// </summary>
        internal static string Dialog_SelectLUTFolder {
            get {
                return ResourceManager.GetString("Dialog_SelectLUTFolder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please fill in all fields with an asterix..
        /// </summary>
        internal static string EmptyFields {
            get {
                return ResourceManager.GetString("EmptyFields", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please fill in all fields with an asterix..
        /// </summary>
        internal static string EmptyFields1 {
            get {
                return ResourceManager.GetString("EmptyFields1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Project database can&apos;t be access, please make sure it&apos;s available or exists..
        /// </summary>
        internal static string Error_AccessDB {
            get {
                return ResourceManager.GetString("Error_AccessDB", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Project database can&apos;t be accessed. Make sure it&apos;s available or exists..
        /// </summary>
        internal static string Error_AccessDB1 {
            get {
                return ResourceManager.GetString("Error_AccessDB1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A value must be selected in all the lists..
        /// </summary>
        internal static string Error_AddGeoline {
            get {
                return ResourceManager.GetString("Error_AddGeoline", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A value must be selected in all the lists..
        /// </summary>
        internal static string Error_AddGeoline1 {
            get {
                return ResourceManager.GetString("Error_AddGeoline1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Workspace can&apos;t be deleted, check for a possible lock..
        /// </summary>
        internal static string Error_CantDeleteWorkspace {
            get {
                return ResourceManager.GetString("Error_CantDeleteWorkspace", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You must enter value for name and id of current selected CGM map..
        /// </summary>
        internal static string Error_CGM {
            get {
                return ResourceManager.GetString("Error_CGM", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Entered style can&apos;t be copied because a file with the same name already exists in style folder..
        /// </summary>
        internal static string Error_CopyStyleFailed {
            get {
                return ResourceManager.GetString("Error_CopyStyleFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Can&apos;t copy.
        /// </summary>
        internal static string Error_CopyTitle {
            get {
                return ResourceManager.GetString("Error_CopyTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to GSC ERROR: A join currently exists on GEO_LINE feature, please remove it to make layer symbol appear correctly. This problem will be corrected..
        /// </summary>
        internal static string Error_DisplayField {
            get {
                return ResourceManager.GetString("Error_DisplayField", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Input file or folder doesn&apos;t exists or is not a valid single copyable file. The copy process didn&apos;t happen. Path:.
        /// </summary>
        internal static string Error_FileOrFolderDontExists {
            get {
                return ResourceManager.GetString("Error_FileOrFolderDontExists", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Missing parameter.
        /// </summary>
        internal static string Error_FileOrFolderDontExistsTitle {
            get {
                return ResourceManager.GetString("Error_FileOrFolderDontExistsTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error found.
        /// </summary>
        internal static string Error_GenericTitle {
            get {
                return ResourceManager.GetString("Error_GenericTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An error was found.
        /// </summary>
        internal static string Error_GenericTitle1 {
            get {
                return ResourceManager.GetString("Error_GenericTitle1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Geoprocessing Failed..
        /// </summary>
        internal static string Error_GeoprocessingFail {
            get {
                return ResourceManager.GetString("Error_GeoprocessingFail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to MISSING SYMBOL.
        /// </summary>
        internal static string Error_GSC_MissingSymbol {
            get {
                return ResourceManager.GetString("Error_GSC_MissingSymbol", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to GSC MISSING SYMBOL.
        /// </summary>
        internal static string Error_GSC_MissingSymbol1 {
            get {
                return ResourceManager.GetString("Error_GSC_MissingSymbol1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to GSC ERROR: Missing feature P_LABELS in database..
        /// </summary>
        internal static string Error_GSC_NoFeaturePlabel {
            get {
                return ResourceManager.GetString("Error_GSC_NoFeaturePlabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to GSC ERROR: Missing feature P_LABELS in database..
        /// </summary>
        internal static string Error_GSC_NoFeaturePlabel1 {
            get {
                return ResourceManager.GetString("Error_GSC_NoFeaturePlabel1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to GSC ERROR: Missing feature GEO_LINES in database..
        /// </summary>
        internal static string Error_GSC_NoGeoline {
            get {
                return ResourceManager.GetString("Error_GSC_NoGeoline", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to GSC ERROR: Missing feature GEO_LINES in database..
        /// </summary>
        internal static string Error_GSC_NoGeoline1 {
            get {
                return ResourceManager.GetString("Error_GSC_NoGeoline1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid coordinate entry..
        /// </summary>
        internal static string Error_InvalidCoord {
            get {
                return ResourceManager.GetString("Error_InvalidCoord", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid geoline type..
        /// </summary>
        internal static string Error_InvalideGeolineType {
            get {
                return ResourceManager.GetString("Error_InvalideGeolineType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid geoline type..
        /// </summary>
        internal static string Error_InvalideGeolineType1 {
            get {
                return ResourceManager.GetString("Error_InvalideGeolineType1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid GEOLINEID value..
        /// </summary>
        internal static string Error_InvalidGeolineID {
            get {
                return ResourceManager.GetString("Error_InvalidGeolineID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid GEOLINEID value..
        /// </summary>
        internal static string Error_InvalidGeolineID1 {
            get {
                return ResourceManager.GetString("Error_InvalidGeolineID1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Selected values for Geoline feature, does not exist within SYMBOL_GEOLINES table..
        /// </summary>
        internal static string Error_InvalidGeolineIDQuery {
            get {
                return ResourceManager.GetString("Error_InvalidGeolineIDQuery", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Selected values for Geoline feature, does not exist within GEOLINE_SYMBOL table..
        /// </summary>
        internal static string Error_InvalidGeolineIDQuery1 {
            get {
                return ResourceManager.GetString("Error_InvalidGeolineIDQuery1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid GEOPOINTID value..
        /// </summary>
        internal static string Error_InvalidGeopointID {
            get {
                return ResourceManager.GetString("Error_InvalidGeopointID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Selected values for Geopoint feature, does not exist within SYMBOL_GEOPOINTS table..
        /// </summary>
        internal static string Error_InvalidGeopointIDQuery {
            get {
                return ResourceManager.GetString("Error_InvalidGeopointIDQuery", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The selected legend item exists within a feature class and cannot be deleted..
        /// </summary>
        internal static string Error_LegendItemExists {
            get {
                return ResourceManager.GetString("Error_LegendItemExists", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SELECTED LEGEND ITEM EXISTS.
        /// </summary>
        internal static string Error_LegendItemExistsTitle {
            get {
                return ResourceManager.GetString("Error_LegendItemExistsTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You must enter value for name and abbreviation of new map unit or a valid value for symbol..
        /// </summary>
        internal static string Error_MapUnit {
            get {
                return ResourceManager.GetString("Error_MapUnit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You must enter value for name and abbreviation of new map unit or a valid value for symbol..
        /// </summary>
        internal static string Error_MapUnit1 {
            get {
                return ResourceManager.GetString("Error_MapUnit1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A given activity wasn&apos;t found inside activity table..
        /// </summary>
        internal static string Error_MissingActicity {
            get {
                return ResourceManager.GetString("Error_MissingActicity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Missing feature from Arc Map project:.
        /// </summary>
        internal static string Error_MissingFeature {
            get {
                return ResourceManager.GetString("Error_MissingFeature", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Couldn&apos;t find one or more key fields in input table: .
        /// </summary>
        internal static string Error_MissingKeyFields {
            get {
                return ResourceManager.GetString("Error_MissingKeyFields", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Can&apos;t find EARTHMATID or STATIONID fields. Make sure input data respects field data schema and has field names exaclty like an original field dataset..
        /// </summary>
        internal static string Error_MissingStructureIDFields {
            get {
                return ResourceManager.GetString("Error_MissingStructureIDFields", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A table is missing inside project database..
        /// </summary>
        internal static string Error_MissingTable {
            get {
                return ResourceManager.GetString("Error_MissingTable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Entered value for Name exceeds the maximum of 25 characters..
        /// </summary>
        internal static string Error_Name25Lenght {
            get {
                return ResourceManager.GetString("Error_Name25Lenght", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Imported feature needs to be polygons in order to work..
        /// </summary>
        internal static string Error_NeedPolygon {
            get {
                return ResourceManager.GetString("Error_NeedPolygon", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Wrong geometry!.
        /// </summary>
        internal static string Error_NeedPolygonTitle {
            get {
                return ResourceManager.GetString("Error_NeedPolygonTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please run set working environment tool in Arc Catalog before launching any tools in Arc Map..
        /// </summary>
        internal static string Error_NoEnvDB {
            get {
                return ResourceManager.GetString("Error_NoEnvDB", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No participant are present in the project..
        /// </summary>
        internal static string Error_NoParticipant {
            get {
                return ResourceManager.GetString("Error_NoParticipant", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please, select a value inside a required list..
        /// </summary>
        internal static string Error_NoSelectedValue {
            get {
                return ResourceManager.GetString("Error_NoSelectedValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No layer was selected in Table of Content, please select one for the tool to work..
        /// </summary>
        internal static string Error_NoSelection {
            get {
                return ResourceManager.GetString("Error_NoSelection", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No feature were selected on the map, please do and restart current tool..
        /// </summary>
        internal static string Error_NoSelectionFeature {
            get {
                return ResourceManager.GetString("Error_NoSelectionFeature", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No defined depositional-unconformable contact detected within geoline feature..
        /// </summary>
        internal static string Error_NoSpecificGeolines {
            get {
                return ResourceManager.GetString("Error_NoSpecificGeolines", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to There is no subtypes within selected layer..
        /// </summary>
        internal static string Error_NoSubtypes {
            get {
                return ResourceManager.GetString("Error_NoSubtypes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You must first enable workspace by clicking &quot;Enable Interfaces&quot; to launch properly this tool..
        /// </summary>
        internal static string Error_NotEnable {
            get {
                return ResourceManager.GetString("Error_NotEnable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You must first enable workspace by clicking &quot;Enable Interfaces&quot; to launch properly this tool..
        /// </summary>
        internal static string Error_NotEnable1 {
            get {
                return ResourceManager.GetString("Error_NotEnable1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enable interfaces.
        /// </summary>
        internal static string Error_NotEnableTitle {
            get {
                return ResourceManager.GetString("Error_NotEnableTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enable interfaces.
        /// </summary>
        internal static string Error_NotEnableTitle1 {
            get {
                return ResourceManager.GetString("Error_NotEnableTitle1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Missing Value in Scientific Language.
        /// </summary>
        internal static string Error_NotInScientificLanguageDictionary {
            get {
                return ResourceManager.GetString("Error_NotInScientificLanguageDictionary", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Missing Value in Scientific Language.
        /// </summary>
        internal static string Error_NotInScientificLanguageDictionary1 {
            get {
                return ResourceManager.GetString("Error_NotInScientificLanguageDictionary1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No valid organisation is attached to selected Person..
        /// </summary>
        internal static string Error_Organisation {
            get {
                return ResourceManager.GetString("Error_Organisation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No valid organisation is attached to selected Person..
        /// </summary>
        internal static string Error_Organisation1 {
            get {
                return ResourceManager.GetString("Error_Organisation1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No valid organisation is attached to selected Person..
        /// </summary>
        internal static string Error_Organisation2 {
            get {
                return ResourceManager.GetString("Error_Organisation2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Entered alias is too long, it must be less than 8 caracters..
        /// </summary>
        internal static string Error_PersonIDTooLong {
            get {
                return ResourceManager.GetString("Error_PersonIDTooLong", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No selected purpose values exists in database..
        /// </summary>
        internal static string Error_PurposeValue {
            get {
                return ResourceManager.GetString("Error_PurposeValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Selected layer is empty, please select a valid feature layer in table of content..
        /// </summary>
        internal static string Error_QC_ConcealedLinesEmptySelectedLayer {
            get {
                return ResourceManager.GetString("Error_QC_ConcealedLinesEmptySelectedLayer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please select a valid feature layer in table of content. Selected layer must be of polygon type..
        /// </summary>
        internal static string Error_QC_ConcealedLinesNoSelectedLayer {
            get {
                return ResourceManager.GetString("Error_QC_ConcealedLinesNoSelectedLayer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Input feature field is restricted, please rename input field: .
        /// </summary>
        internal static string Error_RestrictiedFieldName {
            get {
                return ResourceManager.GetString("Error_RestrictiedFieldName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Spatial Reference mismatch between input feature and feature to append..
        /// </summary>
        internal static string Error_SpatialRefMismatch {
            get {
                return ResourceManager.GetString("Error_SpatialRefMismatch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Already in an edit session, close and restart..
        /// </summary>
        internal static string Error_StartEdit {
            get {
                return ResourceManager.GetString("Error_StartEdit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Already in an edit session, close and restart..
        /// </summary>
        internal static string Error_StartEdit1 {
            get {
                return ResourceManager.GetString("Error_StartEdit1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Project features are not available in Arc Map..
        /// </summary>
        internal static string Error_StartEditFeature {
            get {
                return ResourceManager.GetString("Error_StartEditFeature", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to There might be an existing file lock due to processing by another application/user, be sure to close ArcCatalog or notify the other user..
        /// </summary>
        internal static string Error_StartEditFeature1 {
            get {
                return ResourceManager.GetString("Error_StartEditFeature1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit session was already closed..
        /// </summary>
        internal static string Error_StopEdit {
            get {
                return ResourceManager.GetString("Error_StopEdit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit session was already closed..
        /// </summary>
        internal static string Error_StopEdit1 {
            get {
                return ResourceManager.GetString("Error_StopEdit1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Selected layer contains missing symbols. Still, they will be added to the new layer, but won&apos;t have a proper style and legend description..
        /// </summary>
        internal static string Error_SymbolMistmatch {
            get {
                return ResourceManager.GetString("Error_SymbolMistmatch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Selected layer contains missing symbols. Please refer to symbology to know the problematic codes and edit them. Use a join or a relation with another table or edit symbol with tool &quot;Legend Items&quot;..
        /// </summary>
        internal static string Error_SymbolMistmatch2 {
            get {
                return ResourceManager.GetString("Error_SymbolMistmatch2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Missing Symbol.
        /// </summary>
        internal static string Error_SymbolMistmatchMessageboxTitle {
            get {
                return ResourceManager.GetString("Error_SymbolMistmatchMessageboxTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A symbol wasn&apos;t found in the GSC style. Verify the value is written correctly. Following is the missing symbol value and it&apos;s associated item ID:.
        /// </summary>
        internal static string Error_SymbolMistmatchWithStyle {
            get {
                return ResourceManager.GetString("Error_SymbolMistmatchWithStyle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Too many characters were entered. Limit: .
        /// </summary>
        internal static string Error_TooManyCharacters {
            get {
                return ResourceManager.GetString("Error_TooManyCharacters", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A topology layer already exists within project database..
        /// </summary>
        internal static string Error_TopologyAlreadyExists {
            get {
                return ResourceManager.GetString("Error_TopologyAlreadyExists", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Entered value must be a valid number.
        /// </summary>
        internal static string Error_ValidNumber {
            get {
                return ResourceManager.GetString("Error_ValidNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Entered value must be a valid number.
        /// </summary>
        internal static string Error_ValidNumber1 {
            get {
                return ResourceManager.GetString("Error_ValidNumber1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter dataset is not handle by the tool. Please select a Shapefile, File Geodatabase data, text file or Excel sheet for the load..
        /// </summary>
        internal static string Error_WrongFileType {
            get {
                return ResourceManager.GetString("Error_WrongFileType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Entered feature needs to be point..
        /// </summary>
        internal static string Error_WrongGeometry {
            get {
                return ResourceManager.GetString("Error_WrongGeometry", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An error occured while creating the XY Event for field data. Check field data and make sure there is no unique key duplicate inside table..
        /// </summary>
        internal static string ErrorEventCreation {
            get {
                return ResourceManager.GetString("ErrorEventCreation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Field Data XY Event.
        /// </summary>
        internal static string ErrorEventCreationTitle {
            get {
                return ResourceManager.GetString("ErrorEventCreationTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Extension Not Available.
        /// </summary>
        internal static string ErrorNoExtensionTitle {
            get {
                return ResourceManager.GetString("ErrorNoExtensionTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Maplex Label Engine extension is not available for the moment. Map document will be created without it..
        /// </summary>
        internal static string ErrorNoMaplexInMXD {
            get {
                return ResourceManager.GetString("ErrorNoMaplexInMXD", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to AppendStrucFromGanfeldErrors.
        /// </summary>
        internal static string FileName_FStrucValidation {
            get {
                return ResourceManager.GetString("FileName_FStrucValidation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add.
        /// </summary>
        internal static string FindKeyWord_01 {
            get {
                return ResourceManager.GetString("FindKeyWord_01", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Outputs can be found here: .
        /// </summary>
        internal static string Form_Legend_CreateDataBundleCompleted {
            get {
                return ResourceManager.GetString("Form_Legend_CreateDataBundleCompleted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to BEDROCK.
        /// </summary>
        internal static string GroupLayerBedrock {
            get {
                return ResourceManager.GetString("GroupLayerBedrock", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to EARTH MATERIALS.
        /// </summary>
        internal static string GroupLayerEarthMaterials {
            get {
                return ResourceManager.GetString("GroupLayerEarthMaterials", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to FIELDWORK.
        /// </summary>
        internal static string GroupLayerFieldWork {
            get {
                return ResourceManager.GetString("GroupLayerFieldWork", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to INTERPRETATION.
        /// </summary>
        internal static string GroupLayerInterpretation {
            get {
                return ResourceManager.GetString("GroupLayerInterpretation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PHOTOS.
        /// </summary>
        internal static string GroupLayerPhotos {
            get {
                return ResourceManager.GetString("GroupLayerPhotos", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PROJECT.
        /// </summary>
        internal static string GroupLayerProject {
            get {
                return ResourceManager.GetString("GroupLayerProject", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SAMPLES.
        /// </summary>
        internal static string GroupLayerSamples {
            get {
                return ResourceManager.GetString("GroupLayerSamples", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SOURCE.
        /// </summary>
        internal static string GroupLayerSource {
            get {
                return ResourceManager.GetString("GroupLayerSource", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to STATIONS.
        /// </summary>
        internal static string GroupLayerStations {
            get {
                return ResourceManager.GetString("GroupLayerStations", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to STRUCTURES.
        /// </summary>
        internal static string GroupLayerStruc {
            get {
                return ResourceManager.GetString("GroupLayerStruc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SURFICIAL.
        /// </summary>
        internal static string GroupLayerSurficial {
            get {
                return ResourceManager.GetString("GroupLayerSurficial", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to VALIDATION.
        /// </summary>
        internal static string GroupLayerValidation {
            get {
                return ResourceManager.GetString("GroupLayerValidation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to VISUALIZATION.
        /// </summary>
        internal static string GroupLayerVisualization {
            get {
                return ResourceManager.GetString("GroupLayerVisualization", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;esri:Workspace xmlns:esri=&apos;http://www.esri.com/schemas/ArcGIS/10.6&apos; xmlns:xsi=&apos;http://www.w3.org/2001/XMLSchema-instance&apos; xmlns:xs=&apos;http://www.w3.org/2001/XMLSchema&apos;&gt;&lt;WorkspaceDefinition xsi:type=&apos;esri:WorkspaceDefinition&apos;&gt;&lt;WorkspaceType&gt;esriLocalDatabaseWorkspace&lt;/WorkspaceType&gt;&lt;Version&gt;&lt;/Version&gt;&lt;Domains xsi:type=&apos;esri:ArrayOfDomain&apos;&gt;&lt;Domain xsi:type=&apos;esri:CodedValueDomain&apos;&gt;&lt;DomainName&gt;MapUnit_PID&lt;/DomainName&gt;&lt;FieldType&gt;esriFieldTypeString&lt;/FieldType&gt;&lt;MergePolicy&gt;esriMPTDefaultValue&lt;/MergePolicy&gt;&lt;SplitPo [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string GSC_BEDROCKGDB_SCHEMA_V2_10 {
            get {
                return ResourceManager.GetString("GSC_BEDROCKGDB_SCHEMA_V2_10", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;esri:Workspace xmlns:esri=&apos;http://www.esri.com/schemas/ArcGIS/10.6&apos; xmlns:xsi=&apos;http://www.w3.org/2001/XMLSchema-instance&apos; xmlns:xs=&apos;http://www.w3.org/2001/XMLSchema&apos;&gt;&lt;WorkspaceDefinition xsi:type=&apos;esri:WorkspaceDefinition&apos;&gt;&lt;WorkspaceType&gt;esriLocalDatabaseWorkspace&lt;/WorkspaceType&gt;&lt;Version&gt;&lt;/Version&gt;&lt;Domains xsi:type=&apos;esri:ArrayOfDomain&apos;&gt;&lt;/Domains&gt;&lt;DatasetDefinitions xsi:type=&apos;esri:ArrayOfDataElement&apos;&gt;&lt;DataElement xsi:type=&apos;esri:DETable&apos;&gt;&lt;CatalogPath&gt;/OC=QC_NumericalDataReportTable&lt;/CatalogPath&gt;&lt;Name&gt;QC_Nume [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string GSC_PROJECT_EDITOR_WORKSPACE {
            get {
                return ResourceManager.GetString("GSC_PROJECT_EDITOR_WORKSPACE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Active.
        /// </summary>
        internal static string Keyword_ActivDatabase {
            get {
                return ResourceManager.GetString("Keyword_ActivDatabase", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Build_CGM_.
        /// </summary>
        internal static string Keyword_BuildCGM {
            get {
                return ResourceManager.GetString("Keyword_BuildCGM", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SRC-.
        /// </summary>
        internal static string Keyword_NewSource {
            get {
                return ResourceManager.GetString("Keyword_NewSource", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Main Activity *.
        /// </summary>
        internal static string Label_Activity_RelatedToMainAct {
            get {
                return ResourceManager.GetString("Label_Activity_RelatedToMainAct", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Project *.
        /// </summary>
        internal static string Label_Activity_RelatedToProject {
            get {
                return ResourceManager.GetString("Label_Activity_RelatedToProject", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sub Activity *.
        /// </summary>
        internal static string Label_Activity_SubAct {
            get {
                return ResourceManager.GetString("Label_Activity_SubAct", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add Existing Workspace.
        /// </summary>
        internal static string Message_AddExistingWorkspace {
            get {
                return ResourceManager.GetString("Message_AddExistingWorkspace", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add New Activity.
        /// </summary>
        internal static string Message_AddNewActivity {
            get {
                return ResourceManager.GetString("Message_AddNewActivity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add New Study Area.
        /// </summary>
        internal static string Message_AddNewArea {
            get {
                return ResourceManager.GetString("Message_AddNewArea", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add Existing Database.
        /// </summary>
        internal static string Message_AddNewDatabase {
            get {
                return ResourceManager.GetString("Message_AddNewDatabase", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add New Description.
        /// </summary>
        internal static string Message_AddNewDescription {
            get {
                return ResourceManager.GetString("Message_AddNewDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add New Description.
        /// </summary>
        internal static string Message_AddNewDescription1 {
            get {
                return ResourceManager.GetString("Message_AddNewDescription1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add New Header with option of Legend Order within Legend Display tab..
        /// </summary>
        internal static string Message_AddNewHeader {
            get {
                return ResourceManager.GetString("Message_AddNewHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add New Header.
        /// </summary>
        internal static string Message_AddNewHeader1 {
            get {
                return ResourceManager.GetString("Message_AddNewHeader1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add New Organisation.
        /// </summary>
        internal static string Message_AddNewOrganisation {
            get {
                return ResourceManager.GetString("Message_AddNewOrganisation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Set as New Participant.
        /// </summary>
        internal static string Message_AddNewParticipant {
            get {
                return ResourceManager.GetString("Message_AddNewParticipant", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add New Participant.
        /// </summary>
        internal static string Message_AddNewPerson {
            get {
                return ResourceManager.GetString("Message_AddNewPerson", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add New Project.
        /// </summary>
        internal static string Message_AddNewProject {
            get {
                return ResourceManager.GetString("Message_AddNewProject", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add New Source.
        /// </summary>
        internal static string Message_AddNewsSource {
            get {
                return ResourceManager.GetString("Message_AddNewsSource", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add Custom Style File.
        /// </summary>
        internal static string Message_AddStyle {
            get {
                return ResourceManager.GetString("Message_AddStyle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New Type.
        /// </summary>
        internal static string Message_AddTheme {
            get {
                return ResourceManager.GetString("Message_AddTheme", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Write new theme..
        /// </summary>
        internal static string Message_AddTheme1 {
            get {
                return ResourceManager.GetString("Message_AddTheme1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add New Item Type.
        /// </summary>
        internal static string Message_AddThemeTitle {
            get {
                return ResourceManager.GetString("Message_AddThemeTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New Theme.
        /// </summary>
        internal static string Message_AddThemeTitle1 {
            get {
                return ResourceManager.GetString("Message_AddThemeTitle1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select wanted items..
        /// </summary>
        internal static string Message_AgeItemMessage {
            get {
                return ResourceManager.GetString("Message_AgeItemMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Map Units and Geolines from Legend.
        /// </summary>
        internal static string Message_AgeItemTitle {
            get {
                return ResourceManager.GetString("Message_AgeItemTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create MXD.
        /// </summary>
        internal static string Message_CreateMXD {
            get {
                return ResourceManager.GetString("Message_CreateMXD", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create workspace.
        /// </summary>
        internal static string Message_CreateWorkspace {
            get {
                return ResourceManager.GetString("Message_CreateWorkspace", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select data to load.
        /// </summary>
        internal static string Message_DataPromptTitle {
            get {
                return ResourceManager.GetString("Message_DataPromptTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name.
        /// </summary>
        internal static string Message_EventNameAdd {
            get {
                return ResourceManager.GetString("Message_EventNameAdd", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New Geological Event Name.
        /// </summary>
        internal static string Message_EventNameAddTitle {
            get {
                return ResourceManager.GetString("Message_EventNameAddTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select a feature.
        /// </summary>
        internal static string Message_FeaturePromptTitle {
            get {
                return ResourceManager.GetString("Message_FeaturePromptTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please select path to folder Tools4Project.
        /// </summary>
        internal static string Message_FolderPrompt {
            get {
                return ResourceManager.GetString("Message_FolderPrompt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please select path to folder Tools4Project.
        /// </summary>
        internal static string Message_FolderPrompt1 {
            get {
                return ResourceManager.GetString("Message_FolderPrompt1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select Tools4Project folder..
        /// </summary>
        internal static string Message_FolderPrompt2 {
            get {
                return ResourceManager.GetString("Message_FolderPrompt2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Modify current path?.
        /// </summary>
        internal static string Message_FolderPromptButton {
            get {
                return ResourceManager.GetString("Message_FolderPromptButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Modify current path?.
        /// </summary>
        internal static string Message_FolderPromptButton1 {
            get {
                return ResourceManager.GetString("Message_FolderPromptButton1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tool4Project folder path.
        /// </summary>
        internal static string Message_FolderPromptButton2 {
            get {
                return ResourceManager.GetString("Message_FolderPromptButton2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Current path to Tools4Project folder: .
        /// </summary>
        internal static string Message_FolderPromptTitle {
            get {
                return ResourceManager.GetString("Message_FolderPromptTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Do you wish to change current path to Tools4Project folder: .
        /// </summary>
        internal static string Message_FolderPromptTitle1 {
            get {
                return ResourceManager.GetString("Message_FolderPromptTitle1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Entered structural data is missing key fields, check wheter or not input data comes from Ganfeld..
        /// </summary>
        internal static string Message_FStruc {
            get {
                return ResourceManager.GetString("Message_FStruc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Missing Key Fields.
        /// </summary>
        internal static string Message_FStrucTitle {
            get {
                return ResourceManager.GetString("Message_FStrucTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No Activity exists in database.
        /// </summary>
        internal static string Message_NoMainActivityInDB {
            get {
                return ResourceManager.GetString("Message_NoMainActivityInDB", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No Sub Activity.
        /// </summary>
        internal static string Message_NoSubAct {
            get {
                return ResourceManager.GetString("Message_NoSubAct", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Some data present in the old version didn&apos;t match current Bedrock Project Database schema. They have been transfered into another database: .
        /// </summary>
        internal static string Message_OtherSourceTransfered {
            get {
                return ResourceManager.GetString("Message_OtherSourceTransfered", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Other data sources have been found!.
        /// </summary>
        internal static string Message_OtherSourceTransfered_Title {
            get {
                return ResourceManager.GetString("Message_OtherSourceTransfered_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to All edits were saved..
        /// </summary>
        internal static string Message_SaveEdit {
            get {
                return ResourceManager.GetString("Message_SaveEdit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select CartoElement database.
        /// </summary>
        internal static string Message_SelectCartoElement {
            get {
                return ResourceManager.GetString("Message_SelectCartoElement", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select geodatabase to upgrade.
        /// </summary>
        internal static string Message_SelectOLDPGDB {
            get {
                return ResourceManager.GetString("Message_SelectOLDPGDB", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select a Projection.
        /// </summary>
        internal static string Message_SpatialRefPromptTitle {
            get {
                return ResourceManager.GetString("Message_SpatialRefPromptTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Do you wish to save all changes?.
        /// </summary>
        internal static string Message_StopEdit {
            get {
                return ResourceManager.GetString("Message_StopEdit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Stop Editing.
        /// </summary>
        internal static string Message_StopEditTitle {
            get {
                return ResourceManager.GetString("Message_StopEditTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter current text file column seperator character..
        /// </summary>
        internal static string Message_TextFileSeperatorQuestion {
            get {
                return ResourceManager.GetString("Message_TextFileSeperatorQuestion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Seperator Character.
        /// </summary>
        internal static string Message_TextFileSeperatorTitle {
            get {
                return ResourceManager.GetString("Message_TextFileSeperatorTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Process completed..
        /// </summary>
        internal static string Message_ToolEnds {
            get {
                return ResourceManager.GetString("Message_ToolEnds", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Process completed..
        /// </summary>
        internal static string Message_ToolEnds1 {
            get {
                return ResourceManager.GetString("Message_ToolEnds1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Process completed..
        /// </summary>
        internal static string Message_ToolEnds11 {
            get {
                return ResourceManager.GetString("Message_ToolEnds11", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tool.
        /// </summary>
        internal static string Message_ToolEndsTitle {
            get {
                return ResourceManager.GetString("Message_ToolEndsTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tool.
        /// </summary>
        internal static string Message_ToolEndsTitle1 {
            get {
                return ResourceManager.GetString("Message_ToolEndsTitle1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tool.
        /// </summary>
        internal static string Message_ToolEndsTitle11 {
            get {
                return ResourceManager.GetString("Message_ToolEndsTitle11", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select XML file.
        /// </summary>
        internal static string Message_XMLFilePrompt {
            get {
                return ResourceManager.GetString("Message_XMLFilePrompt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to OID;CODE;DESCRIPTION;FIELD_VALUE
        ///1;01;inclined, upright;inclined, upright
        ///2;02;inclined, overturned &lt; 180;overturned &lt; 180
        ///3;03;inclined, overturned &gt; 180;overturned &gt; 180
        ///4;04;vertical;vertical
        ///5;05;horizontal;horizontal
        ///6;06;inclined;inclined
        ///7;07;horizontal, upright;horizontal, upright
        ///8;08;horizontal, overturned;horizontal, overturned
        ///9;88;undefined;indeterminate
        ///10;88;undefined;not applicable
        ///11;88;undefined;
        ///12;88;undefined; 
        ///13;88;undefined;undefined.
        /// </summary>
        internal static string StrucAttitudeSID {
            get {
                return ResourceManager.GetString("StrucAttitudeSID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to OID;CODE;DESCRIPTION;FIELD_VALUE
        ///1;02;SSS;SSS
        ///2;03;S&gt;L;S&gt;L
        ///3;04;S&gt;=L;S&gt;=L
        ///4;05;S=L;S=L
        ///5;06;S&lt;=L;S&lt;=L
        ///6;07;S&lt;L;S&lt;L
        ///7;08;LLL;LLL
        ///8;01;S tectonite;S tectonite
        ///9;09;L tectonite;L tectonite
        ///10;99;not applicable;not applicable.
        /// </summary>
        internal static string StrucFlatteningSID {
            get {
                return ResourceManager.GetString("StrucFlatteningSID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to OID;CODE;DESCRIPTION;FIELD_VALUE
        ///1;01;first;first
        ///2;02;second;second
        ///3;03;third;third
        ///4;04;fourth;fourth
        ///5;10;primary;primary
        ///6;11;multi-generation;multi-generation
        ///7;88;undefined;undefined
        ///8;66;not entered;
        ///9;66;not entered; 
        ///10;66;not entered;  
        ///11;66;not entered;&quot;;&quot;
        ///12;05;fifth;fifth
        ///13;66;not entered;not entered
        ///14;88;undefined;not applicable.
        /// </summary>
        internal static string StrucGenerationSID {
            get {
                return ResourceManager.GetString("StrucGenerationSID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to OID;CODE;DESCRIPTION;FIELD_VALUE
        ///1;01;measured at station;measured at station
        ///2;02;estimated at station;estimated at station
        ///3;03;estimated remotely;estimated remotely
        ///4;04;calculated from data;calculated from data
        ///5;05;calculated from imagery;calculated from imagery.
        /// </summary>
        internal static string StrucMethodSID {
            get {
                return ResourceManager.GetString("StrucMethodSID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to OID;CODE;DESCRIPTION;FIELD_VALUE
        ///1;01;younging known, sedimentary structure;known, sedimentary structure
        ///2;02;younging known, igneous structure;known, igneous structure
        ///3;03;younging known, stratigraphic order;known, stratigraphic order
        ///4;04;younging inferred, stratigraphic order;inferred, stratigraphic order
        ///5;05;younging inferred, bedding-cleavage ;inferred, bedding-cleavage relations
        ///6;06;younging evidence unknown, historical data;unknown
        ///7;07;no younging evidence;assumed, no evidence
        ///8;07;no you [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string StrucPlanarYoungingSID {
            get {
                return ResourceManager.GetString("StrucPlanarYoungingSID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to OID;CODE;DESCRIPTION;FIELD_VALUE
        ///1;01;no strain;none
        ///2;02;massive;massive
        ///3;03;weak;weak
        ///4;04;moderate;moderate
        ///5;05;strong;strong
        ///6;06;intense;intense.
        /// </summary>
        internal static string StrucStrainSID {
            get {
                return ResourceManager.GetString("StrucStrainSID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to OID;CODE;DESCRIPTION;FIELD_VALUE
        ///1;2001;symmetrical ripple crest;symmetrical ripple crest
        ///2;2002;asymmetrical ripple paleoflow;asymmetrical ripple paleoflow
        ///3;2003;imbrication paleoflow;imbrication paleoflow
        ///4;2004;flute;flute
        ///5;2005;tool mark;tool mark
        ///6;2006;prod mark;prod mark
        ///7;2007;parting lineation;parting lineation
        ///8;2008;trough axis;trough axis
        ///9;2009;slump fold hinge;slump fold hinge
        ///10;2010;slump fold hinge, Z;slump fold hinge, Z
        ///11;2011;slump fold hinge, S;slump fold hinge, S
        ///12;2012; [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string StrucSubsetLinearSID {
            get {
                return ResourceManager.GetString("StrucSubsetLinearSID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to OID;CODE;DESCRIPTION;FIELD_VALUE;RELATEDTO
        ///1;1001;bedding;bedding;
        ///2;1003;igneous layering;igneous layering;
        ///3;1004;igneous layering, pillows;igneous layering, pillows;
        ///4;1005;flow layering;flow layering;
        ///5;1006;compositional layering;compositional layering;
        ///6;1007;crossbed foreset;cross-bed foreset;
        ///7;1008;contact;contact;
        ///8;1009;dyke margin;dyke margin;
        ///9;1010;sill margin;sill margin;
        ///10;1011;vein margin;vein margin;
        ///11;1012;joint;joint;
        ///12;1013;fracture;fracture;
        ///13;1014;fracture zone margin [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string StrucSubsetPlanarSID {
            get {
                return ResourceManager.GetString("StrucSubsetPlanarSID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Validation results could be either: \n -A query layer added to VALIDATION group layer in the Table of Content or \n -Create a report in project workspace folder ..\\ProjectFolder\\Report or \n -Make the correction needed directly to the data..
        /// </summary>
        internal static string Text_ButtonInfo_01 {
            get {
                return ResourceManager.GetString("Text_ButtonInfo_01", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to All validations steps will: \n -Create layers in TOC of the current MXD under Validation&apos;s layer group or \n -Create a report folder in folder ..\\ProjectFolder\\Report or \n -Make the correction..
        /// </summary>
        internal static string Text_ButtonInfo_011 {
            get {
                return ResourceManager.GetString("Text_ButtonInfo_011", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Geolcode.
        /// </summary>
        internal static string Text_ParticipantGeolcode {
            get {
                return ResourceManager.GetString("Text_ParticipantGeolcode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Geolcode.
        /// </summary>
        internal static string Text_ParticipantGeolcode1 {
            get {
                return ResourceManager.GetString("Text_ParticipantGeolcode1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Remarks.
        /// </summary>
        internal static string Text_PartipantRemarks {
            get {
                return ResourceManager.GetString("Text_PartipantRemarks", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Remarks.
        /// </summary>
        internal static string Text_PartipantRemarks1 {
            get {
                return ResourceManager.GetString("Text_PartipantRemarks1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter a Role Description.
        /// </summary>
        internal static string Text_RoleDescription {
            get {
                return ResourceManager.GetString("Text_RoleDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter a Role Description.
        /// </summary>
        internal static string Text_RoleDescription1 {
            get {
                return ResourceManager.GetString("Text_RoleDescription1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Item Color Code: {0}Orange: Map Units{0}Blue: Geolines{0}Green: Geopoints{0}White: Headers{0}Pink: Others.
        /// </summary>
        internal static string ToolTip_LegendOrderListBox {
            get {
                return ResourceManager.GetString("ToolTip_LegendOrderListBox", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Warning.
        /// </summary>
        internal static string Warning_BasicTitle {
            get {
                return ResourceManager.GetString("Warning_BasicTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Warning.
        /// </summary>
        internal static string Warning_BasicTitle1 {
            get {
                return ResourceManager.GetString("Warning_BasicTitle1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please select a theme before loading any data..
        /// </summary>
        internal static string Warning_CartoAttribute {
            get {
                return ResourceManager.GetString("Warning_CartoAttribute", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The current version of Working_Environment.gdb was deprecated, a new version was added. You&apos;ll need to go to customize in order to re-initialize your settings..
        /// </summary>
        internal static string Warning_EnvDBChanged {
            get {
                return ResourceManager.GetString("Warning_EnvDBChanged", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The current version of Working_Environment.gdb was deprecated, a new version was added. You&apos;ll need to go to customize in order to re-initialize your settings..
        /// </summary>
        internal static string Warning_EnvDBChanged1 {
            get {
                return ResourceManager.GetString("Warning_EnvDBChanged1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A copy with the same name already existed, it has been renamed with current date, and new file has been copied..
        /// </summary>
        internal static string Warning_ExistingFile {
            get {
                return ResourceManager.GetString("Warning_ExistingFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Some errors from Ganfeld data has been found. For more details, a text file is available here:.
        /// </summary>
        internal static string Warning_FStrucValidationErrorFound {
            get {
                return ResourceManager.GetString("Warning_FStrucValidationErrorFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Validation errors.
        /// </summary>
        internal static string Warning_FStrucValidationErrorFoundTitle {
            get {
                return ResourceManager.GetString("Warning_FStrucValidationErrorFoundTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No station were selected..
        /// </summary>
        internal static string Warning_GanfeldNoStations {
            get {
                return ResourceManager.GetString("Warning_GanfeldNoStations", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please select only one station..
        /// </summary>
        internal static string Warning_GanfeldTooManyStations {
            get {
                return ResourceManager.GetString("Warning_GanfeldTooManyStations", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Selected map does not have a legend table view associated to it. Please create one with tool Create Temporary Table for Legend Generator..
        /// </summary>
        internal static string Warning_LegendExport_MissingTable {
            get {
                return ResourceManager.GetString("Warning_LegendExport_MissingTable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please select a valid legend table name before continuing..
        /// </summary>
        internal static string Warning_LegendImport_MissingLegendTable {
            get {
                return ResourceManager.GetString("Warning_LegendImport_MissingLegendTable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Detected some missing fonts, please installed proper project fonts..
        /// </summary>
        internal static string Warning_MissingFonts {
            get {
                return ResourceManager.GetString("Warning_MissingFonts", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A topology feature wasn&apos;t found in database. Process will keep going..
        /// </summary>
        internal static string Warning_MissingTopology {
            get {
                return ResourceManager.GetString("Warning_MissingTopology", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Multiple Symbol Code.
        /// </summary>
        internal static string Warning_MultiFGDCFoundTitle {
            get {
                return ResourceManager.GetString("Warning_MultiFGDCFoundTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to More then one symbol code were found in feature, only first one will be used in project legend..
        /// </summary>
        internal static string Warning_MultipleFGDCFound {
            get {
                return ResourceManager.GetString("Warning_MultipleFGDCFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No CGM maps available within feature..
        /// </summary>
        internal static string Warning_NoCGM {
            get {
                return ResourceManager.GetString("Warning_NoCGM", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No Items available within table..
        /// </summary>
        internal static string Warning_NoLegendItem {
            get {
                return ResourceManager.GetString("Warning_NoLegendItem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No overprint were found inside the project, thus no overprint layer will be created..
        /// </summary>
        internal static string Warning_NoOverprintFound {
            get {
                return ResourceManager.GetString("Warning_NoOverprintFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Missing data.
        /// </summary>
        internal static string Warning_NoOverprintFoundTitle {
            get {
                return ResourceManager.GetString("Warning_NoOverprintFoundTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Not yet implemented....
        /// </summary>
        internal static string Warning_NotImplemented {
            get {
                return ResourceManager.GetString("Warning_NotImplemented", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Not yet implemented....
        /// </summary>
        internal static string Warning_NotImplemented1 {
            get {
                return ResourceManager.GetString("Warning_NotImplemented1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Participant Domain can&apos;t be cleaned up of old value, please refresh manually..
        /// </summary>
        internal static string Warning_ParticipantDomainCleanUp {
            get {
                return ResourceManager.GetString("Warning_ParticipantDomainCleanUp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No concealed Geolines that touches boundaries of selected feature layer were found..
        /// </summary>
        internal static string Warning_QC_ConcealedLinesEmptyTouchLayer {
            get {
                return ResourceManager.GetString("Warning_QC_ConcealedLinesEmptyTouchLayer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No concealed Geolines that falls completely inside the boundaries of selected feature layer were found..
        /// </summary>
        internal static string Warning_QC_ConcealedLinesEmptyWithinLayer {
            get {
                return ResourceManager.GetString("Warning_QC_ConcealedLinesEmptyWithinLayer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No problem was detected..
        /// </summary>
        internal static string Warning_QC_GenericNoProblem {
            get {
                return ResourceManager.GetString("Warning_QC_GenericNoProblem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to All labels are unique within all map units..
        /// </summary>
        internal static string Warning_QC_NoDiffLabel {
            get {
                return ResourceManager.GetString("Warning_QC_NoDiffLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No Geoline with field value &quot;IsBoundary&quot; = No was found..
        /// </summary>
        internal static string Warning_QC_NoIsBoundNo {
            get {
                return ResourceManager.GetString("Warning_QC_NoIsBoundNo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No Geoline with field value &quot;IsBoundary&quot; = Yes was found..
        /// </summary>
        internal static string Warning_QC_NoIsBoundYes {
            get {
                return ResourceManager.GetString("Warning_QC_NoIsBoundYes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to All map units contains at least one label..
        /// </summary>
        internal static string Warning_QC_NoLabel {
            get {
                return ResourceManager.GetString("Warning_QC_NoLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No neighbouring Map Units with same label value found..
        /// </summary>
        internal static string Warning_QC_NoSameAdjLabel {
            get {
                return ResourceManager.GetString("Warning_QC_NoSameAdjLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No neighbouring Map Units with same label value found..
        /// </summary>
        internal static string Warning_QC_NoSameAdjLabel1 {
            get {
                return ResourceManager.GetString("Warning_QC_NoSameAdjLabel1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No stations were found within field station feature..
        /// </summary>
        internal static string Warning_QC_NoStations {
            get {
                return ResourceManager.GetString("Warning_QC_NoStations", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No mismatch found..
        /// </summary>
        internal static string Warning_QC_NoStationXYMismatch {
            get {
                return ResourceManager.GetString("Warning_QC_NoStationXYMismatch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No lonely Map Unit found..
        /// </summary>
        internal static string Warning_QC_OrphanMU {
            get {
                return ResourceManager.GetString("Warning_QC_OrphanMU", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No lonely Map Unit found..
        /// </summary>
        internal static string Warning_QC_OrphanMU1 {
            get {
                return ResourceManager.GetString("Warning_QC_OrphanMU1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Deleting a legend item from a project cannot be undone. Are you sure you want to delete this item?.
        /// </summary>
        internal static string Warning_RemoveItemFromProject {
            get {
                return ResourceManager.GetString("Warning_RemoveItemFromProject", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DELETE SELECTED LEGEND ITEM?.
        /// </summary>
        internal static string Warning_RemoveItemFromProjectTitle {
            get {
                return ResourceManager.GetString("Warning_RemoveItemFromProjectTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to All changes were saved..
        /// </summary>
        internal static string Warning_StopEdit {
            get {
                return ResourceManager.GetString("Warning_StopEdit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to All changes were saved..
        /// </summary>
        internal static string Warning_StopEdit1 {
            get {
                return ResourceManager.GetString("Warning_StopEdit1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Current ArcMap layers are not related to an active project geodatabase. Would you like to set them as active?.
        /// </summary>
        internal static string WarningQuestion_WrongProject {
            get {
                return ResourceManager.GetString("WarningQuestion_WrongProject", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to English.
        /// </summary>
        internal static string Word_English {
            get {
                return ResourceManager.GetString("Word_English", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to French.
        /// </summary>
        internal static string Word_French {
            get {
                return ResourceManager.GetString("Word_French", resourceCulture);
            }
        }
    }
}
